const {
    adminUrl,
    ajaxUrl,
    didDisconnect,
    otisBaseUrl,
    otisaiPluginVersion,
    loginUrl,
    pluginPath,
    ajaxNonce,
    restNonce,
    redirectNonce,
    plugins,
    phpVersion,
    portalId,
    portalEmail,
    iframeUrl,
    accountName,
    routes,
    theme,
    wpVersion,
    portalDomain,
    otisaiQueryParamsKeys,
  } = window.otisaiConfig;
  
  export {
    adminUrl,
    ajaxUrl,
    didDisconnect,
    otisBaseUrl,
    otisaiPluginVersion,
    loginUrl,
    pluginPath,
    ajaxNonce,
    restNonce,
    redirectNonce,
    plugins,
    phpVersion,
    portalId,
    portalEmail,
    iframeUrl,
    accountName,
    routes,
    theme,
    wpVersion,
    portalDomain,
    otisaiQueryParamsKeys,
  };
  